server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productsdb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC

management:
  endpoints:
    web:
      exposure:
        include: "*"

log:
  appName: products-default