server:
  port: 8761

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    appname: service-registry-cluster
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 20
    eviction-interval-timer-in-ms: 20000
    peer-node-read-timeout-ms: 20000
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF